/**
 * action 类型
 */
export const REQUEST_HEADLINE = 'REQUEST_HEADLINE';
export const RECEIVE_HEADLINE = 'RECEIVE_HEADLINE';
export const ERROR_HEADLINE = 'ERROR_HEADLINE';


export const REQUEST_GET_HEADLINE = 'REQUEST_GET_HEADLINE';
export const RECEIVE_GET_HEADLINE = 'RECEIVE_GET_HEADLINE';
export const ERROR_GET_HEADLINE = 'ERROR_GET_HEADLINE';
