/**
 * action 类型
 */
export const REQUEST_HEADLINE = 'REQUEST_HEADLINE';
export const RECEIVE_HEADLINE = 'RECEIVE_HEADLINE';
export const ERROR_HEADLINE = 'ERROR_HEADLINE';


export const REQUEST_GET_HEADLINE = 'REQUEST_GET_HEADLINE';
export const RECEIVE_GET_HEADLINE = 'RECEIVE_GET_HEADLINE';
export const ERROR_GET_HEADLINE = 'ERROR_GET_HEADLINE';


export const REQUEST_DELE_HEADLINE = 'REQUEST_DELE_HEADLINE';
export const RECEIVE_DELE_HEADLINE = 'RECEIVE_DELE_HEADLINE';
export const ERROR_DELE_HEADLINE = 'ERROR_DELE_HEADLINE';


export const REQUEST_POST_NEWSLIST = 'REQUEST_POST_NEWSLIST';
export const RECEIVE_POST_NEWSLIST = 'RECEIVE_POST_NEWSLIST';
export const ERROR_POST_NEWSLIST = 'ERROR_POST_NEWSLIST';


export const REQUEST_GET_NEWSLIST = 'REQUEST_GET_NEWSLIST';
export const RECEIVE_GET_NEWSLIST = 'RECEIVE_GET_NEWSLIST';
export const ERROR_GET_NEWSLIST = 'ERROR_GET_NEWSLIST';


export const REQUEST_DELE_NEWSLIST = 'REQUEST_DELE_NEWSLIST';
export const RECEIVE_DELE_NEWSLIST = 'RECEIVE_DELE_NEWSLIST';
export const ERROR_DELE_NEWSLIST = 'ERROR_DELE_NEWSLIST';
